### ISSUE TITLE
stoq starting fail

### ISSUE THREAD

**Issue by Akityo** [V1D1AN/S1EM#59]
## Environment

1. OS (where S1EM server runs): { e.g. Mac OS 10, Windows 10, Ubuntu 16.4, etc. }
2. S1EM version: { e.g. S1EM 1.0.2 }
4. Other environment details:

## Reproducible Steps

5c45131fe946   v1d1an/stoq:3.0.5                                                          "stoq run -a yara ha…"   9 minutes ago    Restarting (1) 58 seconds ago                                                                                                                                                                                          stoq

docker logs stoq

```
stoq.exceptions.StoqPluginException: Mwdb API Key was not provided
{"asctime": "2022-04-24 09:51:14,292", "levelname": "DEBUG", "name": "stoq", "message": "Writing logs to /home/stoq/.stoq/logs/stoq.log"}
Traceback (most recent call last):
  File "/usr/local/bin/stoq", line 33, in <module>
    sys.exit(load_entry_point('stoq-framework==3.0.1', 'console_scripts', 'stoq')())
  File "/usr/local/lib/python3.7/site-packages/stoq_framework-3.0.1-py3.7.egg/stoq/cli.py", line 294, in main
    plugin_dir_list=args.plugin_dir,
  File "/usr/local/lib/python3.7/site-packages/stoq_framework-3.0.1-py3.7.egg/stoq/core.py", line 470, in __init__
    d: self.load_plugin(d) for d in dest_archivers if d  # type: ignore
  File "/usr/local/lib/python3.7/site-packages/stoq_framework-3.0.1-py3.7.egg/stoq/core.py", line 470, in <dictcomp>
    d: self.load_plugin(d) for d in dest_archivers if d  # type: ignore
  File "/usr/local/lib/python3.7/site-packages/stoq_framework-3.0.1-py3.7.egg/stoq/plugin_manager.py", line 177, in load_plugin
    plugin = plugin_class(plugin_config)
  File "/home/stoq/.stoq/plugins/mwdb/mwdb.py", line 45, in __init__
    raise StoqPluginException("Mwdb API Key was not provided")
stoq.exceptions.StoqPluginException: Mwdb API Key was not provided
{"asctime": "2022-04-24 09:52:15,042", "levelname": "DEBUG", "name": "stoq", "message": "Writing logs to /home/stoq/.stoq/logs/stoq.log"}
Traceback (most recent call last):
  File "/usr/local/bin/stoq", line 33, in <module>
    sys.exit(load_entry_point('stoq-framework==3.0.1', 'console_scripts', 'stoq')())
  File "/usr/local/lib/python3.7/site-packages/stoq_framework-3.0.1-py3.7.egg/stoq/cli.py", line 294, in main
    plugin_dir_list=args.plugin_dir,
  File "/usr/local/lib/python3.7/site-packages/stoq_framework-3.0.1-py3.7.egg/stoq/core.py", line 470, in __init__
    d: self.load_plugin(d) for d in dest_archivers if d  # type: ignore
  File "/usr/local/lib/python3.7/site-packages/stoq_framework-3.0.1-py3.7.egg/stoq/core.py", line 470, in <dictcomp>
    d: self.load_plugin(d) for d in dest_archivers if d  # type: ignore
  File "/usr/local/lib/python3.7/site-packages/stoq_framework-3.0.1-py3.7.egg/stoq/plugin_manager.py", line 177, in load_plugin
    plugin = plugin_class(plugin_config)
  File "/home/stoq/.stoq/plugins/mwdb/mwdb.py", line 45, in __init__
    raise StoqPluginException("Mwdb API Key was not provided")
stoq.exceptions.StoqPluginException: Mwdb API Key was not provided
```

docker logs mwdb-web

```172.18.0.19 - - [24/Apr/2022:09:50:47 +0000] "POST /api/auth/login HTTP/1.1" 502 157 "-" "mwdblib/4.1.0 python-requests/2.27.1" "-"
2022/04/24 09:50:57 [error] 10#10: *75 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.19, server: mwdb-web, request: "POST /api/auth/login HTTP/1.1", upstream: "http://172.18.0.24:8080/api/auth/login", host: "mwdb-web"
172.18.0.19 - - [24/Apr/2022:09:50:57 +0000] "POST /api/auth/login HTTP/1.1" 502 157 "-" "mwdblib/4.1.0 python-requests/2.27.1" "-"
2022/04/24 09:51:07 [error] 10#10: *75 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.19, server: mwdb-web, request: "POST /api/auth/login HTTP/1.1", upstream: "http://172.18.0.24:8080/api/auth/login", host: "mwdb-web"
172.18.0.19 - - [24/Apr/2022:09:51:07 +0000] "POST /api/auth/login HTTP/1.1" 502 157 "-" "mwdblib/4.1.0 python-requests/2.27.1" "-"
172.18.0.19 - - [24/Apr/2022:09:51:17 +0000] "POST /api/auth/login HTTP/1.1" 502 157 "-" "mwdblib/4.1.0 python-requests/2.27.1" "-"
2022/04/24 09:51:17 [error] 10#10: *75 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.19, server: mwdb-web, request: "POST /api/auth/login HTTP/1.1", upstream: "http://172.18.0.24:8080/api/auth/login", host: "mwdb-web"
2022/04/24 09:51:17 [error] 10#10: *82 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.19, server: mwdb-web, request: "POST /api/auth/login HTTP/1.1", upstream: "http://172.18.0.24:8080/api/auth/login", host: "mwdb-web"
172.18.0.19 - - [24/Apr/2022:09:51:17 +0000] "POST /api/auth/login HTTP/1.1" 502 157 "-" "mwdblib/4.1.0 python-requests/2.27.1" "-"
172.18.0.19 - - [24/Apr/2022:09:51:27 +0000] "POST /api/auth/login HTTP/1.1" 502 157 "-" "mwdblib/4.1.0 python-requests/2.27.1" "-"
2022/04/24 09:51:27 [error] 10#10: *82 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.19, server: mwdb-web, request: "POST /api/auth/login HTTP/1.1", upstream: "http://172.18.0.24:8080/api/auth/login", host: "mwdb-web"
2022/04/24 09:51:37 [error] 10#10: *82 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.19, server: mwdb-web, request: "POST /api/auth/login HTTP/1.1", upstream: "http://172.18.0.24:8080/api/auth/login", host: "mwdb-web"
172.18.0.19 - - [24/Apr/2022:09:51:37 +0000] "POST /api/auth/login HTTP/1.1" 502 157 "-" "mwdblib/4.1.0 python-requests/2.27.1" "-"
```

docker logs mwdb
```
psql: error: connection to server at "postgres" (172.18.0.12), port 5432 failed: FATAL:  password authentication failed for user "mwdb"
Waiting for postgres
psql: error: connection to server at "postgres" (172.18.0.12), port 5432 failed: FATAL:  password authentication failed for user "mwdb"
Waiting for postgres
psql: error: connection to server at "postgres" (172.18.0.12), port 5432 failed: FATAL:  password authentication failed for user "mwdb"
Waiting for postgres
psql: error: connection to server at "postgres" (172.18.0.12), port 5432 failed: FATAL:  password authentication failed for user "mwdb"
Waiting for postgres
psql: error: connection to server at "postgres" (172.18.0.12), port 5432 failed: FATAL:  password authentication failed for user "mwdb"
Waiting for postgres
psql: error: connection to server at "postgres" (172.18.0.12), port 5432 failed: FATAL:  password authentication failed for user "mwdb"
Waiting for postgres
psql: error: connection to server at "postgres" (172.18.0.12), port 5432 failed: FATAL:  password authentication failed for user "mwdb"
Waiting for postgres
psql: error: connection to server at "postgres" (172.18.0.12), port 5432 failed: FATAL:  password authentication failed for user "mwdb"
```

## Screenshots (optional)

**Comment by Akityo** [comment]
same with https://github.com/V1D1AN/S1EM/issues/56

**Comment by V1D1AN** [comment]
If you have any idea for improve S1EM. Tell me.

**Comment by Akityo** [comment]
@V1D1AN maybe you can change Elastalert to   https://github.com/johnsusek/praeco  :)

Praeco is an alerting tool for Elasticsearch – a GUI for [ElastAlert 2](https://github.com/jertel/elastalert2), using the [ElastAlert API](https://github.com/johnsusek/elastalert-server).

Interactively build alerts for your Elasticsearch data using a query builder
Preview results in an interactive chart
Test your alerts against historical data
Send notifications to Slack, MS Teams, Email, Telegram, Jira, Line Notify, Mattermost, Command, Gitter, Amazon SNS, Amazon SES, Zabbix, Twilio, PagerTree, Exotel, GoogleChat, Stomp, Splunk On-Call (Formerly VictorOps), ServiceNow, Chatwork, Discord, TheHive, Alerta, Datadog, Rocket.Chat, PagerDuty, Tencent SMS or an HTTP POST/HTTP POST 2 endpoint
Supports the Any, Blacklist, Whitelist, Change, Frequency, Flatline, Spike, Cardinality, New Term, and Metric Aggregation rule types
View logs of when your alerts check, fire and fail
